namespace Shopping_Assistant
{
    partial class SignUpScreen
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        /// //this method sets all of the visual aspects of the objects located on the form as well as the form itself (mostly autogenerated while designing the form from the designer)
        /// //non-auto generated additions will have comments added after the line of code
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(SignUpScreen));
            this.label2 = new System.Windows.Forms.Label();
            this.newFNameTextBox = new System.Windows.Forms.TextBox();
            this.newLNameTextBox = new System.Windows.Forms.TextBox();
            this.newEAddressTextBox = new System.Windows.Forms.TextBox();
            this.newPasswordTextBox = new System.Windows.Forms.TextBox();
            this.confirmPasswordTextBox = new System.Windows.Forms.TextBox();
            this.newFNameLabel = new System.Windows.Forms.Label();
            this.newLNameLabel = new System.Windows.Forms.Label();
            this.newEAddressLabel = new System.Windows.Forms.Label();
            this.newPasswordLabel = new System.Windows.Forms.Label();
            this.confirmPasswordLabel = new System.Windows.Forms.Label();
            this.newUserSubmitButton = new System.Windows.Forms.Button();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.newUserCancelButton = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // label2
            // 
            this.label2.BackColor = System.Drawing.Color.OrangeRed;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.White;
            this.label2.Location = new System.Drawing.Point(0, 0);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(284, 52);
            this.label2.TabIndex = 4;
            this.label2.Text = "Sign Up";
            this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // newFNameTextBox
            // 
            this.newFNameTextBox.ForeColor = System.Drawing.SystemColors.GrayText;
            this.newFNameTextBox.Location = new System.Drawing.Point(22, 116);
            this.newFNameTextBox.Name = "newFNameTextBox";
            this.newFNameTextBox.Size = new System.Drawing.Size(236, 20);
            this.newFNameTextBox.TabIndex = 5;
            this.newFNameTextBox.Text = "First Name";
            this.newFNameTextBox.TextChanged += new System.EventHandler(this.newFNameTextBox_TextChanged);//creates an event handler for changing text
            this.newFNameTextBox.Enter += new System.EventHandler(this.newFNameTextBox_Enter);//creates an event handler for when a user enters the textbox
            this.newFNameTextBox.Leave += new System.EventHandler(this.newFNameTextBox_Leave);//creates an event handler for when the user leaves the textbox
            // 
            // newLNameTextBox
            // 
            this.newLNameTextBox.ForeColor = System.Drawing.SystemColors.GrayText;
            this.newLNameTextBox.Location = new System.Drawing.Point(22, 166);
            this.newLNameTextBox.Name = "newLNameTextBox";
            this.newLNameTextBox.Size = new System.Drawing.Size(236, 20);
            this.newLNameTextBox.TabIndex = 6;
            this.newLNameTextBox.Text = "Last Name";
            this.newLNameTextBox.TextChanged += new System.EventHandler(this.newLNameTextBox_TextChanged);//creates an event handler for changing text
            this.newLNameTextBox.Enter += new System.EventHandler(this.newLNameTextBox_Enter);//creates an event handler for when a user enters the textbox
            this.newLNameTextBox.Leave += new System.EventHandler(this.newLNameTextBox_Leave);//creates an event handler for when the user leaves the textbox
            // 
            // newEAddressTextBox
            // 
            this.newEAddressTextBox.ForeColor = System.Drawing.SystemColors.GrayText;
            this.newEAddressTextBox.Location = new System.Drawing.Point(22, 216);
            this.newEAddressTextBox.Name = "newEAddressTextBox";
            this.newEAddressTextBox.Size = new System.Drawing.Size(236, 20);
            this.newEAddressTextBox.TabIndex = 7;
            this.newEAddressTextBox.Text = "Email Address";
            this.newEAddressTextBox.TextChanged += new System.EventHandler(this.newEAddressTextBox_TextChanged);//creates an event handler for changing text
            this.newEAddressTextBox.Enter += new System.EventHandler(this.newEAddressTextBox_Enter);//creates an event handler for when a user enters the textbox
            this.newEAddressTextBox.Leave += new System.EventHandler(this.newEAddressTextBox_Leave);//creates an event handler for when the user leaves the textbox
            // 
            // newPasswordTextBox
            // 
            this.newPasswordTextBox.ForeColor = System.Drawing.SystemColors.GrayText;
            this.newPasswordTextBox.Location = new System.Drawing.Point(22, 263);
            this.newPasswordTextBox.Name = "newPasswordTextBox";
            this.newPasswordTextBox.Size = new System.Drawing.Size(236, 20);
            this.newPasswordTextBox.TabIndex = 8;
            this.newPasswordTextBox.Text = "Password";
            this.newPasswordTextBox.TextChanged += new System.EventHandler(this.newPasswordTextBox_TextChanged);//creates an event handler for changing text
            this.newPasswordTextBox.Enter += new System.EventHandler(this.newPasswordTextBox_Enter);//creates an event handler for when a user enters the textbox
            this.newPasswordTextBox.Leave += new System.EventHandler(this.newPasswordTextBox_Leave);//creates an event handler for when the user leaves the textbox
            // 
            // confirmPasswordTextBox
            // 
            this.confirmPasswordTextBox.ForeColor = System.Drawing.SystemColors.GrayText;
            this.confirmPasswordTextBox.Location = new System.Drawing.Point(22, 310);
            this.confirmPasswordTextBox.Name = "confirmPasswordTextBox";
            this.confirmPasswordTextBox.Size = new System.Drawing.Size(236, 20);
            this.confirmPasswordTextBox.TabIndex = 9;
            this.confirmPasswordTextBox.Text = "Confirm Password";
            this.confirmPasswordTextBox.TextChanged += new System.EventHandler(this.confirmPasswordTextBox_TextChanged);//creates an event handler for changing text
            this.confirmPasswordTextBox.Enter += new System.EventHandler(this.confirmPasswordTextBox_Enter);//creates an event handler for when a user enters the textbox
            this.confirmPasswordTextBox.Leave += new System.EventHandler(this.confirmPasswordTextBox_Leave);//creates an event handler for when the user leaves the textbox
            // 
            // newFNameLabel
            // 
            this.newFNameLabel.AutoSize = true;
            this.newFNameLabel.Location = new System.Drawing.Point(19, 96);
            this.newFNameLabel.Name = "newFNameLabel";
            this.newFNameLabel.Size = new System.Drawing.Size(60, 13);
            this.newFNameLabel.TabIndex = 11;
            this.newFNameLabel.Text = "First Name:";
            // 
            // newLNameLabel
            // 
            this.newLNameLabel.AutoSize = true;
            this.newLNameLabel.Location = new System.Drawing.Point(19, 146);
            this.newLNameLabel.Name = "newLNameLabel";
            this.newLNameLabel.Size = new System.Drawing.Size(61, 13);
            this.newLNameLabel.TabIndex = 12;
            this.newLNameLabel.Text = "Last Name:";
            // 
            // newEAddressLabel
            // 
            this.newEAddressLabel.AutoSize = true;
            this.newEAddressLabel.Location = new System.Drawing.Point(19, 196);
            this.newEAddressLabel.Name = "newEAddressLabel";
            this.newEAddressLabel.Size = new System.Drawing.Size(76, 13);
            this.newEAddressLabel.TabIndex = 13;
            this.newEAddressLabel.Text = "Email Address:";
            // 
            // newPasswordLabel
            // 
            this.newPasswordLabel.AutoSize = true;
            this.newPasswordLabel.Location = new System.Drawing.Point(19, 243);
            this.newPasswordLabel.Name = "newPasswordLabel";
            this.newPasswordLabel.Size = new System.Drawing.Size(56, 13);
            this.newPasswordLabel.TabIndex = 14;
            this.newPasswordLabel.Text = "Password:";
            // 
            // confirmPasswordLabel
            // 
            this.confirmPasswordLabel.AutoSize = true;
            this.confirmPasswordLabel.Location = new System.Drawing.Point(19, 290);
            this.confirmPasswordLabel.Name = "confirmPasswordLabel";
            this.confirmPasswordLabel.Size = new System.Drawing.Size(94, 13);
            this.confirmPasswordLabel.TabIndex = 15;
            this.confirmPasswordLabel.Text = "Confirm Password:";
            // 
            // newUserSubmitButton
            // 
            this.newUserSubmitButton.BackColor = System.Drawing.Color.CornflowerBlue;
            this.newUserSubmitButton.FlatAppearance.BorderColor = System.Drawing.Color.Black;
            this.newUserSubmitButton.FlatAppearance.BorderSize = 3;
            this.newUserSubmitButton.FlatAppearance.MouseDownBackColor = System.Drawing.SystemColors.MenuHighlight;
            this.newUserSubmitButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.newUserSubmitButton.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.newUserSubmitButton.ForeColor = System.Drawing.Color.Black;
            this.newUserSubmitButton.Location = new System.Drawing.Point(163, 349);
            this.newUserSubmitButton.Name = "newUserSubmitButton";
            this.newUserSubmitButton.Size = new System.Drawing.Size(95, 32);
            this.newUserSubmitButton.TabIndex = 16;
            this.newUserSubmitButton.Text = "Submit";
            this.newUserSubmitButton.UseVisualStyleBackColor = false;
            this.newUserSubmitButton.Click += new System.EventHandler(this.newUserSubmitButton_Click);
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(-2, 0);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(286, 17);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox1.TabIndex = 17;
            this.pictureBox1.TabStop = false;
            // 
            // newUserCancelButton
            // 
            this.newUserCancelButton.BackColor = System.Drawing.Color.CornflowerBlue;
            this.newUserCancelButton.FlatAppearance.BorderColor = System.Drawing.Color.Black;
            this.newUserCancelButton.FlatAppearance.BorderSize = 3;
            this.newUserCancelButton.FlatAppearance.MouseDownBackColor = System.Drawing.SystemColors.MenuHighlight;
            this.newUserCancelButton.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(128)))));
            this.newUserCancelButton.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.newUserCancelButton.ForeColor = System.Drawing.Color.Black;
            this.newUserCancelButton.Location = new System.Drawing.Point(22, 349);
            this.newUserCancelButton.Name = "newUserCancelButton";
            this.newUserCancelButton.Size = new System.Drawing.Size(95, 32);
            this.newUserCancelButton.TabIndex = 18;
            this.newUserCancelButton.Text = "Cancel";
            this.newUserCancelButton.UseVisualStyleBackColor = false;
            this.newUserCancelButton.Click += new System.EventHandler(this.newUserCancelButton_Click);
            // 
            // SignUpScreen
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(284, 444);
            this.Controls.Add(this.newUserCancelButton);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.newUserSubmitButton);
            this.Controls.Add(this.confirmPasswordLabel);
            this.Controls.Add(this.newPasswordLabel);
            this.Controls.Add(this.newEAddressLabel);
            this.Controls.Add(this.newLNameLabel);
            this.Controls.Add(this.newFNameLabel);
            this.Controls.Add(this.confirmPasswordTextBox);
            this.Controls.Add(this.newPasswordTextBox);
            this.Controls.Add(this.newEAddressTextBox);
            this.Controls.Add(this.newLNameTextBox);
            this.Controls.Add(this.newFNameTextBox);
            this.Controls.Add(this.label2);
            this.Name = "SignUpScreen";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Shopping Assistant";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.signUpFormClose_Closing);//creates an event handler for when the form is closing via the "X" button
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TextBox newFNameTextBox;
        private System.Windows.Forms.TextBox newLNameTextBox;
        private System.Windows.Forms.TextBox newEAddressTextBox;
        private System.Windows.Forms.TextBox newPasswordTextBox;
        private System.Windows.Forms.TextBox confirmPasswordTextBox;
        private System.Windows.Forms.Label newFNameLabel;
        private System.Windows.Forms.Label newLNameLabel;
        private System.Windows.Forms.Label newEAddressLabel;
        private System.Windows.Forms.Label newPasswordLabel;
        private System.Windows.Forms.Label confirmPasswordLabel;
        private System.Windows.Forms.Button newUserSubmitButton;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.Button newUserCancelButton;
    }
}